{% set name = "pyprocessmacro" %}
{% set version = "1.0.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyProcessMacro-{{ version }}.tar.gz
  sha256: a8728a8c150e7d4fc06fd2cf374ce75f9fd2ded3287c4a1a0c703341fa68de15

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - numpy
    - pandas
    - scipy
    - seaborn
    - matplotlib-base

  run:
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pandas') }}
    - python >={{ python_min }}
    - scipy
    - seaborn

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyprocessmacro

about:
  home: https://github.com/QuentinAndre/pyprocessmacro/
  summary: A Python library for moderation, mediation and conditional process analysis. Based on Andrew F. Hayes Process Macro.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - QuentinAndre
